version: '2'

services: 
    server:
        build: ./server
        container_name: pea
        volumes_from:
            - volume
        networks:
            pea_net:
                ipv4_address: 172.27.0.101
    volume:
        build: ./volume
        volumes:
            - ../www/:/var/www/html
            - ./server/logs/:/var/log/apache2

networks:
    pea_net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.27.0.0/24
